### ISSUE TITLE
请教：正负样本训练方式如何进行？

### ISSUE THREAD

**Issue by YihaoWEI** [hfrommane/TF-siamesenet#2]
嗨！
关于网络的正负样本对，请问是一种怎样的训练方式呢？是triplet loss么？

**Comment by Kill11** [comment]
直接将cnn输出的两组特征相减，将所有特征差输入到单个感知机内，输出结果，然后把结果与样本标签带入交叉熵损失函数（Cross Entropy Loss）

**Comment by YihaoWEI** [comment]
感谢 @Kill11 大神指教！  学习了 orz
